# Generated by Django 5.0.6 on 2024-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('co_name', models.CharField(max_length=64, unique=True)),
                ('last_price', models.FloatField()),
                ('change', models.FloatField(null=True)),
            ],
        ),
    ]
