# Generated by Django 5.0.6 on 2024-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
