# Generated by Django 5.0.6 on 2024-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_userstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
